# [**Fugue and DuckDB: Fast SQL Code in Python**](https://towardsdatascience.com/fugue-and-duckdb-fast-sql-code-in-python-e2e2dfc0f8eb)

In [1]:
from fugue_notebook import setup
import fugue_duckdb

setup()

In [2]:
import os

save_path = os.getcwd() + '/raw.parquet'

In [4]:
import pandas as pd
df=pd.read_parquet(save_path)
df

,Open,High,Low,Close,Volume,Close_time,Quote_asset_volume,Number_of_trades,Taker_buy_base_asset_volume,Taker_buy_quote_asset_volume,symbol,time
0,0.000436,0.000436,0.000436,0.000436,2018.00,1509494459999,0.880400,4,0.00,0.000000,SNGLSETH,2017-11-01 00:00:00
1,0.000436,0.000436,0.000421,0.000425,2497.00,1509494519999,1.074549,8,893.00,0.379605,SNGLSETH,2017-11-01 00:01:00
2,0.000425,0.000428,0.000425,0.000428,2671.00,1509494579999,1.139313,3,2671.00,1.139313,SNGLSETH,2017-11-01 00:02:00
3,0.000428,0.000428,0.000428,0.000428,1773.00,1509494639999,0.758578,4,1773.00,0.758578,SNGLSETH,2017-11-01 00:03:00
4,0.000428,0.000428,0.000428,0.000428,887.00,1509494699999,0.379715,4,887.00,0.379715,SNGLSETH,2017-11-01 00:04:00
...,...,...,...,...,...,...,...,...,...,...,...,...
46674263,7.689900,7.689900,7.629700,7.647400,3031.78,1514678219999,23197.569353,42,8.23,63.152327,BNBUSDT,2017-12-30 23:56:00
46674264,7.647000,7.647000,7.646700,7.646700,5.99,1514678279999,45.804333,3,5.99,45.804333,BNBUSDT,2017-12-30 23:57:00
46674265,7.645300,7.645300,7.536000,7.624100,3103.35,1514678339999,23504.789627,40,466.72,3567.580772,BNBUSDT,2017-12-30 23:58:00
46674266,7.572100,7.601200,7.536100,7.594700,1573.17,1514678399999,11899.882665,32,1450.23,10971.899718,BNBUSDT,2017-12-30 23:59:00
46674267,7.578300,7.596900,7.578300,7.578400,172.21,1514678459999,1307.272823,11,36.73,279.034137,BNBUSDT,2017-12-31 00:00:00

In [5]:
%%fsql duck
LOAD '{{save_path}}'
PRINT

,Open,High,Low,Close,Volume,Close_time,Quote_asset_volume,Number_of_trades,Taker_buy_base_asset_volume,Taker_buy_quote_asset_volume,symbol,time
0,0.000436,0.000436,0.000436,0.000436,2018.0,1509494459999,0.880400,4,0.0,0.000000,SNGLSETH,2017-11-01 00:00:00
1,0.000436,0.000436,0.000421,0.000425,2497.0,1509494519999,1.074549,8,893.0,0.379605,SNGLSETH,2017-11-01 00:01:00
2,0.000425,0.000428,0.000425,0.000428,2671.0,1509494579999,1.139313,3,2671.0,1.139313,SNGLSETH,2017-11-01 00:02:00
3,0.000428,0.000428,0.000428,0.000428,1773.0,1509494639999,0.758578,4,1773.0,0.758578,SNGLSETH,2017-11-01 00:03:00
4,0.000428,0.000428,0.000428,0.000428,887.0,1509494699999,0.379715,4,887.0,0.379715,SNGLSETH,2017-11-01 00:04:00
5,0.000428,0.000428,0.000428,0.000428,0.0,1509494759999,0.000000,0,0.0,0.000000,SNGLSETH,2017-11-01 00:05:00
6,0.000428,0.000428,0.000428,0.000428,0.0,1509494819999,0.000000,0,0.0,0.000000,SNGLSETH,2017-11-01 00:06:00
7,0.000428,0.000428,0.000428,0.000428,0.0,1509494879999,0.000000,0,0.0,0.000000,SNGLSETH,2017-11-01 00:07:00
8,0.000428,0.000428,0.000428,0.000428,0.0,1509494939999,0.000000,0,0.0,0.000000,SNGLSETH,2017-11-01 00:08:00
9,0.000428,0.000428,0.000428,0.000428,0.0,1509494999999,0.000000,0,0.0,0.000000,SNGLSETH,2017-11-01 00:09:00